### PR TITLE
Ios/app/blank

### PR DESCRIPTION
**Pull request by theofandrich**

### CODE REVIEW

**Comment by polymorpher** [comment]
Can't compile

image

**Comment by polymorpher** [comment]
@nageshkumarmishra several files that define class extensions are missing, so the code couldn't compile. Can you add them?

**Comment by nageshkumarmishra** [comment]
@polymorpher, I have made the necessary updates to the pull request. Can you please verify it now?

**Comment by polymorpher** [comment]
looks good, thanks

**Pull request merged**
